<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="wwwroot\html\index.html" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="wwwroot\html\index.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <ProjectReference Include="..\Core.Configuration\Core.Configuration.csproj" />

    <ProjectReference Include="..\Core.Json\Core.Json.csproj" />
  </ItemGroup>

</Project>
