<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="5.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Json\Core.Json.csproj" />
    <ProjectReference Include="..\Core.Permission\Core.Permission.csproj" />
  </ItemGroup>

</Project>
