<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<LangVersion>latest</LangVersion>
		<Version>6.0.0</Version>
		<Authors>gaobo</Authors>
		<Description>asp net core basic framework</Description>
		<PackageProjectUrl>https://github.com/Boy-boy/CoreFramework</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Ddd.Domain\Core.Ddd.Domain.csproj" />
		<ProjectReference Include="..\Core.Json\Core.Json.csproj" />
		<ProjectReference Include="..\Core.Uow\Core.Uow.csproj" />
	</ItemGroup>

</Project>
