<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<ImplicitUsings>$(ImplicitUsings)</ImplicitUsings>
		<Nullable>$(Nullable)</Nullable>
		<LangVersion>$(LangVersion)</LangVersion>
		<Version>$(Version)</Version>
		<Authors>$(Authors)</Authors>
		<Description>$(Description)</Description>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Ddd.Domain\Core.Ddd.Domain.csproj" />
		<ProjectReference Include="..\Core.Json\Core.Json.csproj" />
		<ProjectReference Include="..\Core.Uow\Core.Uow.csproj" />
	</ItemGroup>

</Project>
