<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <PackageProjectUrl>https://github.com/Boy-boy/CoreFramework</PackageProjectUrl>
    <Authors>gaobo</Authors>
    <Version>3.1.9.12</Version>
    <Description>asp net core basic framework</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Json\Core.Json.csproj" />
    <ProjectReference Include="..\Core.Modularity\Core.Modularity.csproj" />
  </ItemGroup>

</Project>
