<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<LangVersion>latest</LangVersion>
		<Version>6.0.1</Version>
		<Authors>gaobo</Authors>
		<Description>asp net core basic framework</Description>
		<PackageProjectUrl>https://github.com/Boy-boy/CoreFramework</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Infrastructure\Core.Infrastructure.csproj" />
		<ProjectReference Include="..\Core.Json\Core.Json.csproj" />
		<ProjectReference Include="..\Core.Modularity\Core.Modularity.csproj" />
	</ItemGroup>

</Project>
