<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<LangVersion>latest</LangVersion>
		<Version>10.0.0</Version>
		<Authors>gaobo</Authors>
		<Description>asp net core basic framework</Description>
		<PackageProjectUrl>https://github.com/Boy-boy/CoreFramework</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
</Project>