<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>$(TargetFramework)</TargetFramework>
	  <ImplicitUsings>$(ImplicitUsings)</ImplicitUsings>
	  <Nullable>$(Nullable)</Nullable>
	  <LangVersion>$(LangVersion)</LangVersion>
	  <Version>$(Version)</Version>
	  <Authors>$(Authors)</Authors>
	  <Description>$(Description)</Description>
	  <PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
	  <PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

</Project>
