<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(TargetFramework)</TargetFramework>
		<ImplicitUsings>$(ImplicitUsings)</ImplicitUsings>
		<Nullable>$(Nullable)</Nullable>
		<LangVersion>$(LangVersion)</LangVersion>
		<Version>$(Version)</Version>
		<Authors>$(Authors)</Authors>
		<Description>$(Description)</Description>
		<PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
		<PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.EventBus\Core.EventBus.csproj" />
		<ProjectReference Include="..\Core.Modularity\Core.Modularity.csproj" />
		<ProjectReference Include="..\Core.RabbitMQ\Core.RabbitMQ.csproj" />
	</ItemGroup>

</Project>
