<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <ImplicitUsings>$(ImplicitUsings)</ImplicitUsings>
    <Nullable>$(Nullable)</Nullable>
    <LangVersion>$(LangVersion)</LangVersion>
    <Version>$(Version)</Version>
    <Authors>$(Authors)</Authors>
    <Description>$(Description)</Description>
    <PackageProjectUrl>$(PackageProjectUrl)</PackageProjectUrl>
    <PackageLicenseExpression>$(PackageLicenseExpression)</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" VersionOverride="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Alert\Core.Alert.csproj" />
  </ItemGroup>

</Project>
