/*
Core.Scheduling.Quartz — AdoJobStore 建表脚本 (SqlServer)
适用版本: Quartz 3.13.x
表前缀  : QRTZ_  (默认值; 改了请同时调整 QuartzSchedulingOptions.TablePrefix)
启用条件: QuartzSchedulingOptions.PersistenceMode = SqlServer
*/

IF OBJECT_ID(N'QRTZ_FIRED_TRIGGERS', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.QRTZ_CALENDARS
    (
        SCHED_NAME    NVARCHAR(120) NOT NULL,
        CALENDAR_NAME NVARCHAR(200) NOT NULL,
        CALENDAR      VARBINARY(MAX) NOT NULL,
        CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
    );

    CREATE TABLE dbo.QRTZ_JOB_DETAILS
    (
        SCHED_NAME        NVARCHAR(120) NOT NULL,
        JOB_NAME          NVARCHAR(150) NOT NULL,
        JOB_GROUP         NVARCHAR(150) NOT NULL,
        DESCRIPTION       NVARCHAR(250) NULL,
        JOB_CLASS_NAME    NVARCHAR(250) NOT NULL,
        IS_DURABLE        BIT NOT NULL,
        IS_NONCONCURRENT  BIT NOT NULL,
        IS_UPDATE_DATA    BIT NOT NULL,
        REQUESTS_RECOVERY BIT NOT NULL,
        JOB_DATA          VARBINARY(MAX) NULL,
        CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
    );

    CREATE TABLE dbo.QRTZ_TRIGGERS
    (
        SCHED_NAME     NVARCHAR(120) NOT NULL,
        TRIGGER_NAME   NVARCHAR(150) NOT NULL,
        TRIGGER_GROUP  NVARCHAR(150) NOT NULL,
        JOB_NAME       NVARCHAR(150) NOT NULL,
        JOB_GROUP      NVARCHAR(150) NOT NULL,
        DESCRIPTION    NVARCHAR(250) NULL,
        NEXT_FIRE_TIME BIGINT NULL,
        PREV_FIRE_TIME BIGINT NULL,
        PRIORITY       INT NULL,
        TRIGGER_STATE  NVARCHAR(16) NOT NULL,
        TRIGGER_TYPE   NVARCHAR(8) NOT NULL,
        START_TIME     BIGINT NOT NULL,
        END_TIME       BIGINT NULL,
        CALENDAR_NAME  NVARCHAR(200) NULL,
        MISFIRE_INSTR  INT NULL,
        JOB_DATA       VARBINARY(MAX) NULL,
        CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
        CONSTRAINT FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
            REFERENCES dbo.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
    );

    CREATE TABLE dbo.QRTZ_SIMPLE_TRIGGERS
    (
        SCHED_NAME      NVARCHAR(120) NOT NULL,
        TRIGGER_NAME    NVARCHAR(150) NOT NULL,
        TRIGGER_GROUP   NVARCHAR(150) NOT NULL,
        REPEAT_COUNT    INT NOT NULL,
        REPEAT_INTERVAL BIGINT NOT NULL,
        TIMES_TRIGGERED INT NOT NULL,
        CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
        CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
    );

    CREATE TABLE dbo.QRTZ_SIMPROP_TRIGGERS
    (
        SCHED_NAME    NVARCHAR(120) NOT NULL,
        TRIGGER_NAME  NVARCHAR(150) NOT NULL,
        TRIGGER_GROUP NVARCHAR(150) NOT NULL,
        STR_PROP_1    NVARCHAR(512) NULL,
        STR_PROP_2    NVARCHAR(512) NULL,
        STR_PROP_3    NVARCHAR(512) NULL,
        INT_PROP_1    INT NULL,
        INT_PROP_2    INT NULL,
        LONG_PROP_1   BIGINT NULL,
        LONG_PROP_2   BIGINT NULL,
        DEC_PROP_1    NUMERIC(13, 4) NULL,
        DEC_PROP_2    NUMERIC(13, 4) NULL,
        BOOL_PROP_1   BIT NULL,
        BOOL_PROP_2   BIT NULL,
        TIME_ZONE_ID  NVARCHAR(80) NULL,
        CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
        CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
    );

    CREATE TABLE dbo.QRTZ_CRON_TRIGGERS
    (
        SCHED_NAME      NVARCHAR(120) NOT NULL,
        TRIGGER_NAME    NVARCHAR(150) NOT NULL,
        TRIGGER_GROUP   NVARCHAR(150) NOT NULL,
        CRON_EXPRESSION NVARCHAR(120) NOT NULL,
        TIME_ZONE_ID    NVARCHAR(80) NULL,
        CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
        CONSTRAINT FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
    );

    CREATE TABLE dbo.QRTZ_BLOB_TRIGGERS
    (
        SCHED_NAME    NVARCHAR(120) NOT NULL,
        TRIGGER_NAME  NVARCHAR(150) NOT NULL,
        TRIGGER_GROUP NVARCHAR(150) NOT NULL,
        BLOB_DATA     VARBINARY(MAX) NULL,
        CONSTRAINT PK_QRTZ_BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
        CONSTRAINT FK_QRTZ_BLOB_TRIGGERS_QRTZ_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
            REFERENCES dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    );

    CREATE TABLE dbo.QRTZ_FIRED_TRIGGERS
    (
        SCHED_NAME        NVARCHAR(120) NOT NULL,
        ENTRY_ID          NVARCHAR(140) NOT NULL,
        TRIGGER_NAME      NVARCHAR(150) NOT NULL,
        TRIGGER_GROUP     NVARCHAR(150) NOT NULL,
        INSTANCE_NAME     NVARCHAR(200) NOT NULL,
        FIRED_TIME        BIGINT NOT NULL,
        SCHED_TIME        BIGINT NOT NULL,
        PRIORITY          INT NOT NULL,
        STATE             NVARCHAR(16) NOT NULL,
        JOB_NAME          NVARCHAR(150) NULL,
        JOB_GROUP         NVARCHAR(150) NULL,
        IS_NONCONCURRENT  BIT NULL,
        REQUESTS_RECOVERY BIT NULL,
        CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID)
    );

    CREATE TABLE dbo.QRTZ_PAUSED_TRIGGER_GRPS
    (
        SCHED_NAME    NVARCHAR(120) NOT NULL,
        TRIGGER_GROUP NVARCHAR(150) NOT NULL,
        CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
    );

    CREATE TABLE dbo.QRTZ_SCHEDULER_STATE
    (
        SCHED_NAME        NVARCHAR(120) NOT NULL,
        INSTANCE_NAME     NVARCHAR(200) NOT NULL,
        LAST_CHECKIN_TIME BIGINT NOT NULL,
        CHECKIN_INTERVAL  BIGINT NOT NULL,
        CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
    );

    CREATE TABLE dbo.QRTZ_LOCKS
    (
        SCHED_NAME NVARCHAR(120) NOT NULL,
        LOCK_NAME  NVARCHAR(40) NOT NULL,
        CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME)
    );

    CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON dbo.QRTZ_JOB_DETAILS (SCHED_NAME, REQUESTS_RECOVERY);
    CREATE INDEX IDX_QRTZ_J_GRP          ON dbo.QRTZ_JOB_DETAILS (SCHED_NAME, JOB_GROUP);

    CREATE INDEX IDX_QRTZ_T_J            ON dbo.QRTZ_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
    CREATE INDEX IDX_QRTZ_T_JG           ON dbo.QRTZ_TRIGGERS (SCHED_NAME, JOB_GROUP);
    CREATE INDEX IDX_QRTZ_T_C            ON dbo.QRTZ_TRIGGERS (SCHED_NAME, CALENDAR_NAME);
    CREATE INDEX IDX_QRTZ_T_G            ON dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
    CREATE INDEX IDX_QRTZ_T_STATE        ON dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE);
    CREATE INDEX IDX_QRTZ_T_N_STATE      ON dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);
    CREATE INDEX IDX_QRTZ_T_N_G_STATE    ON dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);
    CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON dbo.QRTZ_TRIGGERS (SCHED_NAME, NEXT_FIRE_TIME);
    CREATE INDEX IDX_QRTZ_T_NFT_ST       ON dbo.QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);
    CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE  ON dbo.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME);
    CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON dbo.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);
    CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON dbo.QRTZ_TRIGGERS (SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);

    CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME      ON dbo.QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME);
    CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY  ON dbo.QRTZ_FIRED_TRIGGERS (SCHED_NAME, INSTANCE_NAME, REQUESTS_RECOVERY);
    CREATE INDEX IDX_QRTZ_FT_J_G                 ON dbo.QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_NAME, JOB_GROUP);
    CREATE INDEX IDX_QRTZ_FT_JG                  ON dbo.QRTZ_FIRED_TRIGGERS (SCHED_NAME, JOB_GROUP);
    CREATE INDEX IDX_QRTZ_FT_T_G                 ON dbo.QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);
    CREATE INDEX IDX_QRTZ_FT_TG                  ON dbo.QRTZ_FIRED_TRIGGERS (SCHED_NAME, TRIGGER_GROUP);
END
GO
